### ISSUE TITLE
fix hlsjs loading

### ISSUE THREAD

**Issue by bbbo** [flowplayer/wordpress-flowplayer#115]
Despite marking "load HLS plugin" in the settings, it is not loaded so the player falls back to using FlashHLS (flowplayerhls.swf) for HLS streams.

The option should load the hlsjs plugin if marked. it should be set to active by default when creating video posts from Drive, but not for external HLS streams since we cannot be sure whether they have the required [CORS](https://flowplayer.org/docs/plugins.html#hlsjs-server-side) headers set.

By default, the plugin should be loaded from our CDN, ie
 `<script src="//releases.flowplayer.org/hlsjs/flowplayer.hlsjs.min.js"></script>`

We should have an option in `/wp-admin/edit.php?post_type=flowplayer5&page=flowplayer5_settings` to set a different path is the user wishes this (use case: new hls.js / hlsjs.js version conflicts with their custom streams)

Perhaps we should creata a "plugin assets" subcategory, where the audio, background and overlay plugins could be defined

![edit video wp test wordpress_2016-09-27_13-21-24](https://cloud.githubusercontent.com/assets/1395672/18872191/6d3381f8-84b9-11e6-88ac-0826d34c945b.png)

**Comment by sigvenss** [comment]
Hi, thanks for your work with the flowplayer WP plugin!
If i understand it correctly the plugin only supports flash when using a HLS feed, not HLSJS?
Thanks

**Comment by sigvenss** [comment]
EDIT: I just edited the frontend/class-flowplayer5-styles-scripts.php file and did what underdude changed, and now it works! Thanks alot guys.

**Comment by bbbo** [comment]
yup, this was a bug in the last release ;)
