### ISSUE TITLE
commercial: default to //releases.flowplayer.org/[version]/commercial/ if license key entered

### ISSUE THREAD

**Issue by bbbo** [flowplayer/wordpress-flowplayer#124]
where version is the same as the free version used in the plugin. Document how to use a local player if needed

**Comment by underdude** [comment]
This kind of was working before if one flipped the switches to correct positions and left the commercial folder url empty, but made it a bit clearer on  https://github.com/flowplayer/wordpress-flowplayer/commit/ccf4f8af84747a6badaaba77dec8e5d0363ae645 .

Usage of a local commercial player is documented on plugin FAQ.
