### ISSUE TITLE
CSS conflict with Yoast SEO CSS

### ISSUE THREAD

**Issue by alibasheer** [flowplayer/wordpress-flowplayer#128]
The styles for class `.switch-light`  in `flowplayer5/admin/assets/css/admin.min.css` is conflicting with Yoast SEO CSS and thus breaking the toggle element in Yoast SEO (e.g. XML Sitemaps page)

I am on:
WordPress version 4.8.2
Yoast SEO version 5.4.2
Flowplayer HTML5 for WordPress version 3.0.2

**Comment by underdude** [comment]
Thanks for the report! I'll fix this.

**Comment by underdude** [comment]
There will be a new plugin release to wp.org soon, but in the meanwhile you can grab the new admin.min.css from https://github.com/flowplayer/wordpress-flowplayer/blob/1c1bbae71f0eb0d790f36bb3789ca2766d90e951/admin/assets/css/admin.min.css and replace the current one.

**Comment by alibasheer** [comment]
Thank you!

I updated the style, and the Yoast SEO switch fixed.
