### ISSUE TITLE
add config option for description_url

### ISSUE THREAD

**Issue by bbbo** [flowplayer/wordpress-flowplayer#87]
on a per video base, add an input field for an url pointing to a metadata html page, urlencode the result and pass as descirption_url parameter in the ad request. 

See https://flowplayer.org/docs/asf.html#requests and https://support.google.com/adsense/answer/1705829?hl=en&ref_topic=1706004

**Comment by grappler** [comment]
@bbbo I have added support. Please can you test it on your test site. I have loaded the latest code your test site.

**Comment by bbbo** [comment]
cool! will test tomorrow morning

**Comment by bbbo** [comment]
the transferral of the desc url works, I currently don't get ads for my setup though. will try with a better video and some text later on.
